server:
  port: 8084
 
spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user/**
        
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path=/hotel/**
        
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path=/rating/**  
          
          
          
eureka:
  instance:
    hostname: localhost
    
    prefer-ip-address: true
  
  client:
    fetch-registry: true
    register-with-eureka: true

#  config:
#    import:
#    - configserver:http://localhost:8085