#  
#spring:
#  application:
#    name: CONFIG-SERVER
#    
#    
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/sumeetk-behera/microservice-config-server
#          clone-on-start: true
#          
#          
#eureka:
#  instance:
#    hostname: localhost
#    
#    prefer-ip-address: true
#  
#  client:
#    fetch-registry: true
#    register-with-eureka: true